### ISSUE TITLE
Changing network causes "EADDRNOTAVAIL" error

### ISSUE THREAD

**Issue by auchenberg** [watson/bonjour#18]
Having a long running process like https://github.com/auchenberg/dinero-printer/, and changing network causes the following error:

<img width="504" alt="screen shot 2016-08-17 at 5 30 24 pm" src="https://cloud.githubusercontent.com/assets/173559/17797885/5830dd52-6581-11e6-913b-ae3727d7f21d.png">

It looks like it's trying to bind to a previous available IP, but the network has changed.

**Comment by thom-nic** [comment]
I see this error just from running with a static IP on the only interface (on mac):
```
en4: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=b<RXCSUM,TXCSUM,VLAN_HWTAGGING>
	ether a0:ce:c8:03:4a:cd 
	inet6 fe80::414:1cc7:30e7:1b17%en4 prefixlen 64 secured scopeid 0xe 
	inet 192.168.8.99 netmask 0xffffff00 broadcast 192.168.8.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect (100baseTX <full-duplex,flow-control>)
	status: active
```
When calling publish:
```
myproj/node_modules/bonjour/lib/mdns-server.js:87
      if (err) throw err // TODO: Handle this (if no callback is given, the error will be ignored)
               ^

Error: send EADDRNOTAVAIL 224.0.0.251:5353
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:405:11)
```

**Comment by gowrav** [comment]
Any solution on how to handle this ?

**Comment by drahnieR** [comment]
I'll suggest remove this, at least, until some message mechanism is implemented. The current implementation will only crash the application, make it pointless.

https://github.com/watson/bonjour/blob/bdc467a4f3c7b9fe8bc54468b6fc4d80b8f1c098/lib/mdns-server.js#L87
